### ISSUE TITLE
xo online, for quick/shareable lints

### ISSUE THREAD

**Issue by fregante** [sindresorhus/project-ideas#104]
Like this https://eslint.org/demo/

But for [xo](https://github.com/sindresorhus/xo)

It could use https://bundle.run/ to just load the latest from npm so one wouldn't need to update it much.

**Comment by sindresorhus** [comment]
Can you open an issue about this on XO too? For discovery.

**Comment by vvanelslande** [comment]
Here you go: https://github.com/vvanelslande/laas

**Comment by bfred-it** [comment]
Interesting service, but that’s an API. I was looking for something I can use and share in the browser

**Comment by vvanelslande** [comment]
It can be used from a browser. you can try it at https://laas.glitch.me/.

**Comment by bfred-it** [comment]
That's a good start, but ideally it would be more usable than that and it would support URL sharing. It's probably easier to re-package eslint's own demo code: https://github.com/eslint/eslint.github.io/tree/master/js/app/demo

**Comment by vvanelslande** [comment]
I added new features:
- URL sharing ([Example](https://laas.glitch.me/#eyJsaW50ZXIiOiJ4byIsImNvZGUiOiJjb25zb2xlLmxvZygnc3R1ZmYnKTtcbiIsInNob3dSdWxlTmFtZXMiOnRydWV9))
- URL linting ([Example](https://laas.glitch.me/#https://cdn.jsdelivr.net/npm/ky@0.9.1/index.min.js))

**Comment by fregante** [comment]
Tracked on XO https://github.com/xojs/xo/issues/261
