### ISSUE TITLE
linkify github usernames

### ISSUE THREAD

**Issue by rarkins** [sindresorhus/project-ideas#111]
I would like the equivalent of https://github.com/sindresorhus/linkify-issues but for GitHub usernames instead. For the purposes of [my app](https://github.com/renovatebot/renovate), I need to:

1. Linkify everything that GitHub would linkify
2. Replace github.com URLs with my own redirector, to prevent "link spam"

So this is part of step 1, to complement `linkify-issues`.

There are some libraries for username matching but perhaps not as complete or succinct as sindresorhus/issue-regex is for building on.

Related:
https://github.com/regexhq/mentions-regex
https://github.com/shinnn/github-username-regex
https://github.com/carlos8f/gfm-linkify

**Comment by yeskunall** [comment]
@rarkins I made something along the lines of what you're looking for https://github.com/yeskunall/linkify-gh-usernames.

I'm not saying it's _exactly_ what you're looking for, but hey, it's a start. LMK how I can make it better.

💖

**Comment by rarkins** [comment]
@yeskunall that's some pretty quick work! Thanks, I will check it out soon - I wasn't expecting to have anything so fast :)
