### ISSUE TITLE
git diff dependency trees

### ISSUE THREAD

**Issue by kiprasmel** [sindresorhus/project-ideas#119]
Often times, I make a lot of cross-related changes before committing them all.

When I'm done with the changes & am ready to commit, I end up in a state where I don't in **what order** to commit the changes.

I'd like to make atomic commits, meaning they're focused on one thing only, and the project works at the commit's state.

To do this, you need to parse your changes & find which changes depend on what other changes, effectively creating dependency trees, and committing the changes from the bottom to the top for each tree.

Now, this is a tedious task to do yourself manually every time, and after getting inspiration from https://github.com/benawad/destiny and https://github.com/pzavolinsky/ts-unused-exports, I think that this would be possible to do automatically.

---

I'd love to implement this myself, but I don't know if I have enough knowledge with dependency resolution & other pitfalls - any help, ideas, resources or contributions would be helpful!

**Comment by sarpik** [comment]
Update:
Working on this @ https://github.com/sarpik/git-diff-order

**Comment by fregante** [comment]
> find which changes depend on what other changes

This is called static analysis and it's not for the faint of heart. There are probably tools that can build a dependency tree of functions across files, like many IDEs/TypeScript do.

> I'd like to make atomic commits, meaning they're focused on one thing only

I also do this, but there's no way that a system can figure out that line 1 from a.js and line 3 from b.js belong to the same "thing", so I'm pretty sure that this request is impossible to fulfill, unless you're ok with it just committing "one function at a time"
