### ISSUE TITLE
Architecture enforcer for JavaScript/TypeScript (like ArchUnit)

### ISSUE THREAD

**Issue by robatwilliams** [sindresorhus/project-ideas#120]
I'd like to be able to explicitly define my architecture and automatically test my application against it.

Things like layers, import constraints.

Motivation: https://www.archunit.org/motivation

More use cases: https://github.com/robatwilliams/enforce-frontend-architecture

**Comment by joakimbeng** [comment]
I have only used it for a short while but https://github.com/sverweij/dependency-cruiser seems to be capable of, at least, some of the stuff you're looking for

**Comment by robatwilliams** [comment]
Thanks, I hadn't come across that tool despite much searching.

I opened an issue on their project (see above) to see if it might be made easier to find.
