### ISSUE TITLE
rfc: Image resizing CLI

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/project-ideas#123]
We could wrap [waifu2x](https://www.npmjs.com/package/waifu2x) as a CLI to compute resized images.

The API could work something like this:

```sh
$ resize image.png --output image.resized.png --resolution 1920x1080
```

We would also need some way to specify noise levels and a scale instead of a resolution.

**Comment by 7rulnik** [comment]
Also, it could be the wrapper around https://github.com/imgproxy/imgproxy

**Comment by Richienb** [comment]
@sindresorhus Do you have any comments on this?

**Comment by forivall** [comment]
Note that for other scaling algorithms, https://npm.im/sharp-cli and https://npm.im/@jimp/cli exist.

**Comment by charliegroll** [comment]
https://npm.im/sharp-cli has `sharp resize <width> [height]` for this same purpose

**Comment by fregante** [comment]
There are infinite solutions for this already, especially since cli tools are not limited to JS. For example there's ImageMagick. Once you figure out the flags it already does what you need and more

**Comment by Richienb** [comment]
Is there a way to resize images in imagemagick using the algorithm present in waifu2x?

**Comment by fregante** [comment]
https://github.com/DeadSix27/waifu2x-converter-cpp literally is a CLI tool already and https://www.npmjs.com/package/waifu2x is a wrapper of that CLI tool.

**Comment by JiangWeixian** [comment]
try `sips`
