### ISSUE TITLE
Automatically generate test skeletons

### ISSUE THREAD

**Issue by fregante** [sindresorhus/project-ideas#65]
This sounds like something complex, but perhaps you have better ideas.

`ava-generate-tests` could generate empty tests by statically analyzing the code, maybe behaving like a coverage tool by figuring out all the ways it could be run (e.g. `isCool` needs to be `true` to go in this `if` statement)

It can't actually build functional tests or figure out what they're supposed to output, but it could at least provide some sort of boilerplate to manually verify.

Example `input.js`:

``` js
export default function (sayHello) {
    if(sayHello) {
        return 'hello';
    }
}
export function strLength (str) {
    return str.length;
}
```

Example `generated-tests.js`:

``` js
import test from 'ava';
import camelizedModuleName, {strLength} from '.';

test('return undefined',t => {
    t.same(camelizedModuleName(), undefined);
});

test('return hello', t => {
    t.same(camelizedModuleName(true), 'hello');
});

test(TBD, t => { // "TBD" would be something the dev would have to replace
    t.same(strLength(TBD), TBD);
});
```

**Comment by sindresorhus** [comment]
That would be really cool!

**Comment by Qix-** [comment]
This is probably the best use case for `Function.length` if there ever was one.

**Comment by conorhastings** [comment]
i can look into working on something like this! have a couple semi similar projects that do some code/test generation
