### ISSUE TITLE
HTML reporter for TAP

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/project-ideas#84]
Originally requested in https://github.com/avajs/ava/issues/1260.

TAP → https://testanything.org/

I couldn't find any good ones. Need something that looks good.

Could maybe adapt https://github.com/adamgruber/mochawesome or https://github.com/blond/mocha-simple-html-reporter for TAP.

Or better yet, create a tap-mocha bridge module, so you can use any Mocha reporter with TAP.

**Comment by zusamann** [comment]
Yes you are right! I opened the original issue because I couldn't figure something out. 
The most straightforward thing I could find was this https://www.npmjs.com/package/tap-to-html

And my apologies to the creator, but it's very ugly.

I think there could be a lot of value in a beautiful TAP -> HTML, given how we find TAP supported libs in all the different languages. So people that have a system that is not only in Client Side JS/NodeJS but also Python,etc... could have an integrated way of writing tests that generate TAP and produce a dashboard from it.

**Comment by rpunkfu** [comment]
Had some free time so I created one, it's rather simple.. I open to suggestions :D
https://github.com/rpunkfu/tap-that-html

**Comment by zusamann** [comment]
@rpunkfu can you tell me what would be the easiest way to save the output html in a file?

```js
"test": "nyc ava --tap | tap-that-html -o reports/test/index.html"
```

**Comment by rpunkfu** [comment]
Hi @zusamann, I see two options here ;)

1. I would have to create functionality to save into file
2. `"test": "mkdir -p reports/test && nyc ava --tap | tap-that-html > reports/test/index.html"`

**Comment by zusamann** [comment]
I did try that actually, but I got a syntax error, something to do with windows?
```
    "lint": "mkdir -p reports/lint && eslint -f node_modules/eslint-tap . | tap-that-html > /reports/lint/index.html",
    "test": "mkdir -p reports/test && nyc ava --tap | tap-that-html > reports/test/index.html",
```

**Comment by zusamann** [comment]
Ok it's a windows issue indeed:
http://stackoverflow.com/questions/39727920/cant-use-mkdir-in-npm-script-from-windows

Solved it with this package:
https://www.npmjs.com/package/mkdirp

**Comment by zusamann** [comment]
Ok it's a windows issue indeed:
http://stackoverflow.com/questions/39727920/cant-use-mkdir-in-npm-script-from-windows

Solved it with this package:
https://www.npmjs.com/package/mkdirp

**Comment by rpunkfu** [comment]
Ahh, didn't know since I don't use windows at all, sorry ;)

**Comment by gabrielcsapo** [comment]
is this still a valid ask? I am wondering if I could take a shot at this!

**Comment by zusamann** [comment]
@gabrielcsapo 

@rpunkfu had created a lib which looks good, but it had some issues which are preventing me from using it, https://github.com/rpunkfu/tap-that-html/issues

You could probably contribute to that repo?

**Comment by gabrielcsapo** [comment]
I was looking for something more like https://github.com/adamgruber/mochawesome so I created https://github.com/gabrielcsapo/tap-html going to see how far I can get, if not I will contribute to the tap-that-html repo, almost done so my bad 🙈

**Comment by rpunkfu** [comment]
@gabrielcsapo if you want, I can transfer repo to you, I don't have time to work on this

**Comment by gabrielcsapo** [comment]
@rpunkfu, If tou need a maintainer I could help maintain your repo, you don't have to transfer it to me

**Comment by rpunkfu** [comment]
@gabrielcsapo added you as a collaborator :)

**Comment by gabrielcsapo** [comment]
😄 woot woot! Thanks @rpunkfu

**Comment by rpunkfu** [comment]
@gabrielcsapo No problem friend :)

**Comment by gabrielcsapo** [comment]
okay I am done formalizing the work I was doing locally (https://github.com/gabrielcsapo/tap-html/). I can still maintain tap-that-html with you @rpunkfu

**Comment by mhassan1** [comment]
Here is a neat project that supports lots of mocha reporters: https://github.com/tapjs/tap-mocha-reporter

**Comment by Richienb** [comment]
I've started building a really simple reporter. Here's a demo: https://rawcdn.githack.com/Richienb/taplet/b2318f19c193b17b49f146dbc826735e55ab765b/out.html

**Comment by Richienb** [comment]
I've just released an initial version. Try this:

```sh
$ npm install --global taplet
$ ava --tap | taplet --outputFile output.html # In your project directory
```

**Comment by Richienb** [comment]
@sindresorhus I think we can close this issue now.
